### ISSUE TITLE
Initial states

### ISSUE THREAD

**Issue by xem** [timhutton/ruletablerepository#3]
Hello,

I don't know if it's already been asked (or answered), but would it be possible to add in your repository the initial states of the automata, where it's applicable?

For example in Langton's loops, one could be interested to know that the "default" initial state is something like:

```
  022222222
  2170140142
  2022222202
  2720000212
  2120000212
  2020000212
  2720000212
  21222222122222
  207107107111112
  02222222222222
```

But when I tried to implement it ( [here](https://jsfiddle.net/f14h6jL4/) ), I had to go on another website to find it.

Thanks!

**Comment by timhutton** [comment]
Hi xem. 

Some of our rules come as zip files that include patterns. Others you can find in Golly (http://golly.sourceforge.net/), like the Langton's Loops one. In fact a good way to use this project is to run Golly and access via Help > Online Archives > Rule Table Repository. This lets you load patterns and rules and run them immediately. 

Tim
